# sql
# ['Alias', 'ClauseElement', 'ClauseVisitor', 'ColumnCollection', 'ColumnElement', 'CompoundSelect', 'Delete', 'False_', 'FromClause', 'Insert', 'Join', 'Select', 'Selectable', 'TableClause', 'TableSample', 'True_', 'Update', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__go', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'alias', 'all_', 'and_', 'annotation', 'any_', 'asc', 'base', 'between', 'bindparam', 'case', 'cast', 'collate', 'column', 'compiler', 'crud', 'ddl', 'default_comparator', 'delete', 'desc', 'distinct', 'dml', 'elements', 'except_', 'except_all', 'exists', 'expression', 'extract', 'false', 'func', 'funcfilter', 'functions', 'insert', 'intersect', 'intersect_all', 'join', 'label', 'lateral', 'literal', 'literal_column', 'modifier', 'naming', 'not_', 'null', 'nullsfirst', 'nullslast', 'operators', 'or_', 'outerjoin', 'outparam', 'over', 'quoted_name', 'schema', 'select', 'selectable', 'sqltypes', 'subquery', 'table', 'tablesample', 'text', 'true', 'tuple_', 'type_api', 'type_coerce', 'union', 'union_all', 'update', 'util', 'visitors', 'within_group']

# sql.expression
# ['Alias', 'BinaryExpression', 'BindParameter', 'BooleanClauseList', 'CTE', 'Case', 'Cast', 'ClauseElement', 'ClauseList', 'CollectionAggregate', 'ColumnClause', 'ColumnCollection', 'ColumnElement', 'CompoundSelect', 'Delete', 'Executable', 'Exists', 'Extract', 'False_', 'FromClause', 'FromGrouping', 'Function', 'FunctionElement', 'FunctionFilter', 'Generative', 'GenerativeSelect', 'Grouping', 'HasCTE', 'HasPrefixes', 'HasSuffixes', 'Insert', 'Join', 'Label', 'Lateral', 'Null', 'Over', 'PARSE_AUTOCOMMIT', 'ReleaseSavepointClause', 'RollbackToSavepointClause', 'SavepointClause', 'ScalarSelect', 'Select', 'SelectBase', 'Selectable', 'TableClause', 'TableSample', 'TextAsFrom', 'TextClause', 'True_', 'Tuple', 'TypeClause', 'TypeCoerce', 'UnaryExpression', 'Update', 'UpdateBase', 'ValuesBase', 'Visitable', 'WithinGroup', '_BinaryExpression', '_BindParamClause', '_Case', '_Cast', '_Executable', '_Exists', '_Extract', '_False', '_FromGrouping', '_Generative', '_Grouping', '_Label', '_Null', '_Over', '_ScalarSelect', '_SelectBase', '_TextClause', '_True', '_Tuple', '_TypeClause', '_UnaryExpression', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_clause_element_as_expr', '_clone', '_cloned_difference', '_cloned_intersection', '_column_as_key', '_corresponding_column_or_error', '_expression_literal_as_text', '_from_objects', '_interpret_as_from', '_is_column', '_labeled', '_literal_as_binds', '_literal_as_label_reference', '_literal_as_text', '_only_column_elements', '_select_iterables', '_string_or_unprintable', '_truncated_label', 'alias', 'all_', 'and_', 'any_', 'asc', 'between', 'bindparam', 'case', 'cast', 'collate', 'column', 'delete', 'desc', 'distinct', 'except_', 'except_all', 'exists', 'extract', 'false', 'func', 'funcfilter', 'insert', 'intersect', 'intersect_all', 'join', 'label', 'lateral', 'literal', 'literal_column', 'modifier', 'not_', 'null', 'nullsfirst', 'nullslast', 'or_', 'outerjoin', 'outparam', 'over', 'public_factory', 'quoted_name', 'select', 'subquery', 'table', 'tablesample', 'text', 'true', 'tuple_', 'type_coerce', 'union', 'union_all', 'update', 'within_group']

# sql.operators.ColumnOperators
# ['__add__', '__and__', '__class__', '__contains__', '__delattr__', '__dir__', '__div__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__invert__', '__le__', '__lshift__', '__lt__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__radd__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__rshift__', '__rsub__', '__rtruediv__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__sub__', '__subclasshook__', '__truediv__', 'all_', 'any_', 'asc', 'between', 'bool_op', 'collate', 'concat', 'contains', 'desc', 'distinct', 'endswith', 'ilike', 'in_', 'is_', 'is_distinct_from', 'isnot', 'isnot_distinct_from', 'like', 'match', 'notilike', 'notin_', 'notlike', 'nullsfirst', 'nullslast', 'op', 'operate', 'reverse_operate', 'startswith', 'timetuple']

# sql.SELECT
# ['__and__', '__bool__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__invert__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__nonzero__', '__or__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__visit_name__', '__weakref__', '_annotate', '_annotations', '_bind', '_clone', '_cloned_set', '_cols_populated', '_columns_plus_names', '_compiler', '_compiler_dispatch', '_constructor', '_copy_internals', '_correlate', '_correlate_except', '_deannotate', '_distinct', '_execute_on_connection', '_execution_options', '_for_update_arg', '_from_cloned', '_from_objects', '_froms', '_generate', '_get_display_froms', '_group_by_clause', '_hide_froms', '_hints', '_init_collections', '_is_clone_of', '_is_from_container', '_is_join', '_is_lateral', '_is_lexical_equivalent', '_is_select', '_label_resolve_dict', '_limit', '_limit_clause', '_memoized_property', '_needs_parens_for_grouping', '_negate', '_offset', '_offset_clause', '_order_by_clause', '_order_by_label_element', '_params', '_populate_column_collection', '_prefixes', '_refresh_for_new_column', '_reset_exported', '_scalar_type', '_select_iterable', '_set_bind', '_setup_prefixes', '_setup_suffixes', '_simple_int_limit', '_simple_int_offset', '_statement_hints', '_suffixes', '_textual', '_translate_schema', '_with_annotations', 'alias', 'append_column', 'append_correlation', 'append_from', 'append_group_by', 'append_having', 'append_order_by', 'append_prefix', 'append_whereclause', 'apply_labels', 'as_scalar', 'autocommit', 'bind', 'c', 'column', 'columns', 'compare', 'compile', 'correlate', 'correlate_except', 'correspond_on_equivalents', 'corresponding_column', 'count', 'cte', 'description', 'distinct', 'except_', 'except_all', 'execute', 'execution_options', 'for_update', 'foreign_keys', 'froms', 'get_children', 'group_by', 'having', 'inner_columns', 'intersect', 'intersect_all', 'is_clause_element', 'is_derived_from', 'is_selectable', 'join', 'label', 'lateral', 'limit', 'locate_all_froms', 'named_with_column', 'offset', 'order_by', 'outerjoin', 'params', 'prefix_with', 'primary_key', 'reduce_columns', 'replace_selectable', 'scalar', 'schema', 'select', 'select_from', 'selectable', 'self_group', 'suffix_with', 'supports_execution', 'tablesample', 'type', 'union', 'union_all', 'unique_params', 'where', 'with_for_update', 'with_hint', 'with_only_columns', 'with_statement_hint']

vs = "나는"
l = ['%s', '%s_', '__%s__']

for i in l:
    print(i % vs)
s = (0 - 1) * 2
print(s)
